channels:
  - conda-forge
dependencies:
  - r-base=4.3.3
  - r-irkernel
  - r-tidyverse
  - r-haven
  - r-remotes
  - r-devtools
  - r-knitr
  - r-rmarkdown
  - r-quarto
  - r-summarytools
  - r-modelsummary
  - r-gt
  - r-ragg
  - r-mgcv
  - r-pacman
